server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 28017
      database: recipes_info
  jpa:
    properties:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipes
    username: recipes
    password: pass
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml


